### ISSUE TITLE
Can't enter decimal in Hours of PTO

### ISSUE THREAD

**Issue by rjlsoftware** [dwatling/fss_pto_calculator#1]
You currently cannot enter a decimal in the Hours of PTO field, for example 33.81 hours of pto. It strips the kepress entry of the decimal.  However, you can go back and edit the field and add the decimal in.

Solution:  I'd like to be able to enter decimal, don't strip it on data entry.

**Comment by dwatling** [comment]
Thanks for the feedback. This issue has been fixed with the latest push.
